### ISSUE TITLE
Opening the scoreboard causes lag

### ISSUE THREAD

**Issue by AgentTroll** [omnibombulator/noto#16]
Hello.

I'm new to noto, but I'm loving it so far. One thing that is a little bothersome, while it doesn't affect gameplay much, is that whenever I press tab to open the scoreboard, there is a lag spike when it opens and when it closes. This did not happen with the stock hud or with other huds.

I understand that you do not specifically provide compatibility for linux, but nevertheless, if you could look into this, it would be great.

**System Information**
- Output of `lsb_release -a`:

```
No LSB modules are available.
Distributor ID:	Debian
Description:	Debian GNU/Linux 8.2 (jessie)
Release:	8.2
Codename:	jessie
```

- Image/kernel version/whatever `uname` pulls out: `3.16.0-4-amd64`
- GeForce GTX 970/PCIe/SSE2, Intel® Core™ i3-3240 CPU @ 3.40GHz × 4
- Graphics driver version (Don't know why this is relevant, but just in case): 352.55 (non-free)

**Comment by ravenx99** [comment]
Valve just fix a general TF2 bug that sounds like what you're experiencing.

- Fixed the scoreboard causing a framerate hitch when it was toggled

**Comment by AgentTroll** [comment]
@ravenx99 Thank you, it turns out it's not the HUD's fault then.
