### ISSUE TITLE
Huntsman & Jarate Bars Overlapping

### ISSUE THREAD

**Issue by Androidify287** [omnibombulator/noto#8]
When the huntsman and jarate are equipped, the bars overlap each other, so you can't see the jarate meter when you have the huntsman out.

When the huntsman is out:
![2014-11-01_00001](https://cloud.githubusercontent.com/assets/1980809/4873897/3f6bd168-622d-11e4-8831-2a64f7b39d4a.jpg)
When the jarate is out:
![2014-11-01_00002](https://cloud.githubusercontent.com/assets/1980809/4873898/4993a01c-622d-11e4-9f38-e3f1a69d781b.jpg)

**Comment by omnibombulator** [comment]
This was done to prevent 2 bars appearing when the Huntsman is drawn.
