### ISSUE TITLE
%HEALTH% displayed overhead on full health

### ISSUE THREAD

**Issue by ThePsionic** [omnibombulator/noto#9]
When other players have full health and you hover over them, %... (what I can assume to be %HEALTH%) is displayed over their heads rather than their current life points. Whether this also happens with übercharge is unknown.

**Comment by ThePsionic** [comment]
Example: http://steamcommunity.com/sharedfiles/filedetails/?id=377253428

**Comment by omnibombulator** [comment]
This is impossible to fix as this is a problem on Valve's end.
